CREATE TABLE "GREEN"."MEMBER" 
   (	"MEMBER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MEMBER_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"MEMBER_PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

INSERT ALL
	INTO GREEN."MEMBER" (MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD) VALUES ('a','12','12')
	INTO GREEN."MEMBER" (MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD) VALUES ('kang','a','1')
	INTO GREEN."MEMBER" (MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD) VALUES ('ba','1aaa','1')
SELECT 1 FROM DUAL;

TRIGGER trg_memberid
AFTER UPDATE OF member_id ON MEMBER for EACH ROW
BEGIN 
	UPDATE MEMBERALLERGY
	SET MEMBER_ID = :NEW.member_id 
	WHERE MEMBER_ID = :OLD.member_id;
END;
